apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcheck-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: healthcheck-role

rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  verbs:
  - get
  - list

- apiGroups: ["apps"]
  resources:
  - deployments
  verbs:
  - get
  - list

- apiGroups: ["route.openshift.io"]
  resources:
  - routes
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healthcheck-rolebinding

subjects:
- kind: ServiceAccount
  name: healthcheck-sa

roleRef:
  kind: Role
  name: healthcheck-role
  apiGroup: rbac.authorization.k8s.io
