apiVersion: v1
kind: Secret
metadata:
  name: mail-secret

type: Opaque

stringData:
  MAIL_USERNAME: tharunreddy802@gmail.com
  MAIL_PASSWORD: bqhu smxy fgtj ntrw
  MAIL_RECEIVER: ctharunreddy2309@gmail.com@gmail.com
